name: IntelliJ Plugin Compatibility (local action)

on:
  push:

jobs:
  compatibility:
    name: Ensure plugin compatibility against 2020.1 & the latest EAP snapshot for both IDEA Community, IDEA Ultimate.

    runs-on: ubuntu-latest

    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build the plugin using Gradle
        run: ./gradlew buildPlugin
        env:
          IS_CI: "True"

      - name: Verify Plugin on IntelliJ Platforms
        id: verify
        uses: ./.github/actions/intellij-platform-plugin-verifier-action
        with:
#          verifier-version: '1.231'
#          plugin-location: 'build/distributions/sample-intellij-plugin-*'
          ide-versions: |
            ideaIC:2020.1
            ideaIU:2020.1
            ideaIC:LATEST-EAP-SNAPSHOT
            ideaIU:LATEST-EAP-SNAPSHOT
#            ideaIU:2020.1
#            ideaIC:LATEST-EAP-SNAPSHOT
#            ideaIU:LATEST-EAP-SNAPSHOT
#            ideaIC:2017.3  # Remove for testing of a successful execution
#            pycharmPC:2019.3.4
#            goland:2019.3.3
#            clion:2019.3.4

      - name: Get log file path and print contents
        run: |
          echo "The log file path is: ${{steps.verify.outputs.verification-output-log-filename}}" ;
          cat ${{steps.verify.outputs.verification-output-log-filename}}