name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install
      - run: |
          npm run all
  test-gh-test-ij-release-update-action: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: 'wait around 1 minute (for debugging)'
        run: |
          date ; sleep 60 ; date

      - uses: ./.github/actions/gh-test-ij-release-update-action
        with:
          milliseconds: 1000

      - name: 'wait around 3 minutes (for debugging)'
        run: |
          date ; sleep 180 ; date
