name: 'IJ Release Update'

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  test-gh-test-ij-release-update-action: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
        with:
          token: ${{ secrets.PAT_TOKEN_FOR_IJ_UPDATE_ACTION }}

      - uses: ChrisCarini/gh-test-ij-release-update-action@main
        with:
          PAT_TOKEN_FOR_IJ_UPDATE_ACTION: ${{ secrets.PAT_TOKEN_FOR_IJ_UPDATE_ACTION }}
