name: 'IJ Release Update'
on: # rebuild any PRs and main branch changes
  pull_request:

  push:
    branches:
      - main
      - 'releases/*'

  workflow_dispatch:

jobs:
  test-gh-test-ij-release-update-action: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/gh-test-ij-release-update-action
